// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Planimaq.backend.Data;

#nullable disable

namespace Planimaq.backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251220123441_AddPlanimaq")]
    partial class AddPlanimaq
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Planimaq.Shared.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Planimaq.Shared.Entities.City", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("stateId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("stateId", "Name")
                        .IsUnique();

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Planimaq.Shared.Entities.Configuracion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("MailData")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Configuraciones");
                });

            modelBuilder.Entity("Planimaq.Shared.Entities.Country", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Planimaq.Shared.Entities.Maestro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("sEstado")
                        .HasColumnType("int");

                    b.Property<string>("sGrupo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("sIdGrupo")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("sValor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("Maestros");
                });

            modelBuilder.Entity("Planimaq.Shared.Entities.Notificacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("DateInitial")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MailData")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("id");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Planimaq.Shared.Entities.Personal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("area_pers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargo_pers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ccosto_pers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codccostotareo_pers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dfeba_pers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dfein_pers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dfena_pers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dhofin_pers")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dhoini_pers")
                        .HasColumnType("datetime2");

                    b.Property<int>("ncode_cargo")
                        .HasColumnType("int");

                    b.Property<int>("ncode_orar")
                        .HasColumnType("int");

                    b.Property<int>("ncond_pers")
                        .HasColumnType("int");

                    b.Property<decimal>("ncostohora_pers")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("nesta_pers")
                        .HasColumnType("int");

                    b.Property<int>("npimpo_pers")
                        .HasColumnType("int");

                    b.Property<string>("sapma_pers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sappa_pers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("scamisatalla_pers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdire_pers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdni_pers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shofin_pers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shoini_pers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("slogo_pers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("smail_pers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("smailcorp_pers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("snomb_pers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("snomc_pers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spantalontalla_pers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stelefono_pers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stelefonocorp_pers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subigeo_pers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("szapatotalla_pers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("vfirma_pers")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("vimagen_pers")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("id");

                    b.ToTable("Personales");
                });

            modelBuilder.Entity("Planimaq.Shared.Entities.Rol", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Planimaq.Shared.Entities.State", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("CountryId", "Name")
                        .IsUnique();

                    b.ToTable("States");
                });

            modelBuilder.Entity("Planimaq.Shared.Entities.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Planimaq.Shared.Entities.City", b =>
                {
                    b.HasOne("Planimaq.Shared.Entities.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("stateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("Planimaq.Shared.Entities.State", b =>
                {
                    b.HasOne("Planimaq.Shared.Entities.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Planimaq.Shared.Entities.Country", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("Planimaq.Shared.Entities.State", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
